/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    Appointment: typeof import('./src/components/features/managementSection/Appointment.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseUpload: typeof import('./src/components/common/BaseUpload.vue')['default']
    Dashboard: typeof import('./src/components/features/managementSection/Dashboard.vue')['default']
    DateTimePicker: typeof import('./src/components/features/appointmentSection/DateTimePicker.vue')['default']
    DetailServiceCard: typeof import('./src/components/common/cards/DetailServiceCard.vue')['default']
    DropDownMenu: typeof import('./src/components/common/DropDownMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Gallery: typeof import('./src/components/features/managementSection/Gallery.vue')['default']
    GalleryCard: typeof import('./src/components/common/cards/GalleryCard.vue')['default']
    GallerySection: typeof import('./src/components/features/homeSections/GallerySection.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HeroSection: typeof import('./src/components/features/homeSections/HeroSection.vue')['default']
    LoginCard: typeof import('./src/components/features/loginSection/LoginCard.vue')['default']
    Membership: typeof import('./src/components/features/managementSection/Membership.vue')['default']
    MenuItem: typeof import('./src/components/common/MenuItem.vue')['default']
    OrderSideBar: typeof import('./src/components/common/OrderSideBar.vue')['default']
    Quote: typeof import('./src/components/features/managementSection/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceButton: typeof import('./src/components/ui/ServiceButton.vue')['default']
    ServiceCard: typeof import('./src/components/common/cards/ServiceCard.vue')['default']
    ServiceItemCard: typeof import('./src/components/common/cards/ServiceItemCard.vue')['default']
    ServiceSection: typeof import('./src/components/features/homeSections/ServiceSection.vue')['default']
    ServiceSelection: typeof import('./src/components/features/appointmentSection/ServiceSelection.vue')['default']
    Stylist: typeof import('./src/components/features/managementSection/Stylist.vue')['default']
    StylistCard: typeof import('./src/components/common/cards/StylistCard.vue')['default']
    StylistSelection: typeof import('./src/components/features/appointmentSection/StylistSelection.vue')['default']
  }
}
